export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const SET_INGREDIENT = "SET_INGREDIENT"
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED"

export const PURCHASE_BURGUER_START = 'PURCHASE_BURGUER_START'
export const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS'
export const PURCHASE_BURGUER_FAIL = 'PURCHASE_BURGUER_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'